### PR TITLE
ROS Kinetic, Ubuntu 16.04 support

### PR DESCRIPTION
**Pull request by bmagyar**
Perhaps this should go on a different branch as it breaks compatibility. Anyways...let me know if there's interest in taking this and I'll create a PR against some other branch. These changes make the package compile on Ubuntu 16.04 with ROS Kinetic and Gazebo 7.

### CODE REVIEW

**Comment by costashatz** [comment]
@bmagyar Thanks for the help.

Right now, I do not have a lot of time, but after mid September I will be able to think about how to organize the repo (dev branches etc). I will get back to you after 15-20 September. Thanks for understanding..

**Comment by vrabaud** [comment]
Any update on that ? Thx !

**Comment by costashatz** [comment]
@bmagyar and @vrabaud is #7 ok for you?

**Comment by costashatz** [comment]
This is handled in #7...

**Pull request closed without merging**
